<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $now = date("Y-m-d H:i:s");

        DB::table("currencies")->insert([
            [
                "name" => "U.S. Dollar",
                "symbol" => '$',
                "exchange_rate" => "1.00000",
                "status" => "1",
                "code" => "USD",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Australian Dollar",
                "symbol" => '$',
                "exchange_rate" => "1.28000",
                "status" => "1",
                "code" => "AUD",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Brazilian Real",
                "symbol" => 'R$',
                "exchange_rate" => "3.25000",
                "status" => "1",
                "code" => "BRL",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Canadian Dollar",
                "symbol" => '$',
                "exchange_rate" => "1.27000",
                "status" => "1",
                "code" => "CAD",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Czech Koruna",
                "symbol" => "Kč",
                "exchange_rate" => "20.65000",
                "status" => "1",
                "code" => "CZK",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Danish Krone",
                "symbol" => "kr",
                "exchange_rate" => "6.05000",
                "status" => "1",
                "code" => "DKK",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Euro",
                "symbol" => "€",
                "exchange_rate" => "0.85000",
                "status" => "1",
                "code" => "EUR",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Hong Kong Dollar",
                "symbol" => '$',
                "exchange_rate" => "7.83000",
                "status" => "1",
                "code" => "HKD",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Hungarian Forint",
                "symbol" => "Ft",
                "exchange_rate" => "255.24000",
                "status" => "1",
                "code" => "HUF",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Israeli New Sheqel",
                "symbol" => "₪",
                "exchange_rate" => "3.48000",
                "status" => "1",
                "code" => "ILS",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Japanese Yen",
                "symbol" => "¥",
                "exchange_rate" => "107.12000",
                "status" => "1",
                "code" => "JPY",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Malaysian Ringgit",
                "symbol" => "RM",
                "exchange_rate" => "3.91000",
                "status" => "1",
                "code" => "MYR",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Mexican Peso",
                "symbol" => '$',
                "exchange_rate" => "18.72000",
                "status" => "1",
                "code" => "MXN",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Norwegian Krone",
                "symbol" => "kr",
                "exchange_rate" => "7.83000",
                "status" => "1",
                "code" => "NOK",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "New Zealand Dollar",
                "symbol" => '$',
                "exchange_rate" => "1.38000",
                "status" => "1",
                "code" => "NZD",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Philippine Peso",
                "symbol" => "₱",
                "exchange_rate" => "52.26000",
                "status" => "1",
                "code" => "PHP",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Polish Zloty",
                "symbol" => "zł",
                "exchange_rate" => "3.39000",
                "status" => "1",
                "code" => "PLN",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Pound Sterling",
                "symbol" => "£",
                "exchange_rate" => "0.72000",
                "status" => "1",
                "code" => "GBP",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Russian Ruble",
                "symbol" => "руб",
                "exchange_rate" => "55.93000",
                "status" => "1",
                "code" => "RUB",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Singapore Dollar",
                "symbol" => '$',
                "exchange_rate" => "1.32000",
                "status" => "1",
                "code" => "SGD",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Swedish Krona",
                "symbol" => "kr",
                "exchange_rate" => "8.19000",
                "status" => "1",
                "code" => "SEK",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Swiss Franc",
                "symbol" => "CHF",
                "exchange_rate" => "0.94000",
                "status" => "1",
                "code" => "CHF",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Thai Baht",
                "symbol" => "฿",
                "exchange_rate" => "31.39000",
                "status" => "1",
                "code" => "THB",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Taka",
                "symbol" => "৳",
                "exchange_rate" => "84.00000",
                "status" => "1",
                "code" => "BDT",
                "created_at" => $now,
                "updated_at" => null,
            ],
            [
                "name" => "Indian Rupee",
                "symbol" => "Rs",
                "exchange_rate" => "68.45000",
                "status" => "1",
                "code" => "Rupee",
                "created_at" => $now,
                "updated_at" => null,
            ],
        ]);
    }
}
