<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $now = date("Y-m-d H:i:s");

        DB::table("districts")->insert([
            [
                "id" => 1,
                "name" => "Jessore",
                "code" => "BD4041",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 2,
                "name" => "Dhaka",
                "code" => "BD3026",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 3,
                "name" => "Bogra",
                "code" => "BD5010",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 4,
                "name" => "Lalmonirhat",
                "code" => "BD5552",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 5,
                "name" => "Barisal",
                "code" => "BD1006",
                "division_id" => 5,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 6,
                "name" => "Habiganj",
                "code" => "BD6036",
                "division_id" => 6,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 7,
                "name" => "Brahamanbaria",
                "code" => "BD2012",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 8,
                "name" => "Joypurhat",
                "code" => "BD5038",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 9,
                "name" => "Chuadanga",
                "code" => "BD4018",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 10,
                "name" => "Faridpur",
                "code" => "BD3029",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 11,
                "name" => "Bandarban",
                "code" => "BD2003",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 12,
                "name" => "Barguna",
                "code" => "BD1004",
                "division_id" => 5,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 13,
                "name" => "Chittagong",
                "code" => "BD2015",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 14,
                "name" => "Narayanganj",
                "code" => "BD3067",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 15,
                "name" => "Satkhira",
                "code" => "BD4087",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 16,
                "name" => "Pabna",
                "code" => "BD5076",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 17,
                "name" => "Netrakona",
                "code" => "BD4572",
                "division_id" => 8,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 18,
                "name" => "Naogaon",
                "code" => "BD5064",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 19,
                "name" => "Panchagarh",
                "code" => "BD5577",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 20,
                "name" => "Kishoreganj",
                "code" => "BD3048",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 21,
                "name" => "Rangpur",
                "code" => "BD5585",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 22,
                "name" => "Natore",
                "code" => "BD5069",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 23,
                "name" => "Bagerhat",
                "code" => "BD4001",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 24,
                "name" => "Rajshahi",
                "code" => "BD5081",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 25,
                "name" => "Rangamati",
                "code" => "BD2084",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 26,
                "name" => "Jamalpur",
                "code" => "BD4539",
                "division_id" => 8,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 27,
                "name" => "Sylhet",
                "code" => "BD6091",
                "division_id" => 6,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 28,
                "name" => "Rajbari",
                "code" => "BD3082",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 29,
                "name" => "Thakurgaon",
                "code" => "BD5594",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 30,
                "name" => "Maulvibazar",
                "code" => "BD6058",
                "division_id" => 6,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 31,
                "name" => "Comilla",
                "code" => "BD2019",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 32,
                "name" => "Tangail",
                "code" => "BD3093",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 33,
                "name" => "Khulna",
                "code" => "BD4047",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 34,
                "name" => "Patuakhali",
                "code" => "BD1078",
                "division_id" => 5,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 35,
                "name" => "Noakhali",
                "code" => "BD2075",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 36,
                "name" => "Narsingdi",
                "code" => "BD3068",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 37,
                "name" => "Sirajganj",
                "code" => "BD5088",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 38,
                "name" => "Mymensingh",
                "code" => "BD4561",
                "division_id" => 8,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 39,
                "name" => "Pirojpur",
                "code" => "BD1079",
                "division_id" => 5,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 40,
                "name" => "Shariatpur",
                "code" => "BD3086",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 41,
                "name" => "Kushtia",
                "code" => "BD4050",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 42,
                "name" => "Bhola",
                "code" => "BD1009",
                "division_id" => 5,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 43,
                "name" => "Nawabganj",
                "code" => "BD5070",
                "division_id" => 3,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 44,
                "name" => "Kurigram",
                "code" => "BD5549",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 45,
                "name" => "Dinajpur",
                "code" => "BD5527",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 46,
                "name" => "Sunamganj",
                "code" => "BD6090",
                "division_id" => 6,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 47,
                "name" => 'Cox\'s Bazar',
                "code" => "BD2022",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 48,
                "name" => "Chandpur",
                "code" => "BD2013",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 49,
                "name" => "Feni",
                "code" => "BD2030",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 50,
                "name" => "Manikganj",
                "code" => "BD3056",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 51,
                "name" => "Khagrachhari",
                "code" => "BD2046",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 52,
                "name" => "Nilphamari",
                "code" => "BD5573",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 53,
                "name" => "Gaibandha",
                "code" => "BD5532",
                "division_id" => 4,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 54,
                "name" => "Meherpur",
                "code" => "BD4057",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 55,
                "name" => "Munshiganj",
                "code" => "BD3059",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 56,
                "name" => "Gazipur",
                "code" => "BD3033",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 57,
                "name" => "Gopalganj",
                "code" => "BD3035",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 58,
                "name" => "Jhenaidah",
                "code" => "BD4044",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 59,
                "name" => "Jhalokati",
                "code" => "BD1042",
                "division_id" => 5,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 60,
                "name" => "Sherpur",
                "code" => "BD4589",
                "division_id" => 8,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 61,
                "name" => "Narail",
                "code" => "BD4065",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 62,
                "name" => "Madaripur",
                "code" => "BD3054",
                "division_id" => 2,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 63,
                "name" => "Lakshmipur",
                "code" => "BD2051",
                "division_id" => 7,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
            [
                "id" => 64,
                "name" => "Magura",
                "code" => "BD4055",
                "division_id" => 1,
                "status" => 1,
                "created_at" => $now,
                "updated_at" => null,
                "deleted_at" => null,
            ],
        ]);
    }
}
