<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $now = date("Y-m-d H:i:s");

        DB::table("permissions")->insert([
            [
                "name" => "view_all_school",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "login_as_school",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_school",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_school",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_school",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_campus",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_campus",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_campus",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_campus",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_shift",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_shift",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_shift",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_shift",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_class",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_class",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_class",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_class",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_section",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_section",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_section",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_section",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_coordinator",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "login_as_coordinator",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_coordinator",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_coordinator",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_coordinator",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_student",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_student",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_student",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_student",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "student_bulk_import",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "student_bulk_export",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_schedule",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_schedule",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_schedule",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_schedule",
                "section" => "school",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_doctors",
                "section" => "doctor",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "login_as_doctor",
                "section" => "doctor",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_doctor",
                "section" => "doctor",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_doctor",
                "section" => "doctor",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_doctor",
                "section" => "doctor",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "in_house_product_sale_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "seller_products_sale_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "products_stock_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "product_wishlist_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "user_search_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "commission_history_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "wallet_transaction_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "earning_report",
                "section" => "report",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_blogs",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_blog",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_blog",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_blog",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "publish_blog",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_blog_categories",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_blog_category",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_blog_category",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_blog_category",
                "section" => "blog",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_flash_deals",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_flash_deal",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_flash_deal",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_flash_deal",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "publish_flash_deal",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "featured_flash_deal",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_coupons",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_coupon",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_coupon",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_coupon",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "send_newsletter",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_subscribers",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_subscriber",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_support_tickets",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "reply_to_support_tickets",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_product_queries",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "reply_to_product_queries",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_product_conversations",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "reply_to_product_conversations",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_product_conversations",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_contacts",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "reply_to_contact",
                "section" => "support",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "header_setup",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "footer_setup",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "website_appearance",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_website_pages",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_website_page",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_website_page",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_website_page",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "select_homepage",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "authentication_layout_settings",
                "section" => "website_setup",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "general_settings",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "features_activation",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "language_setup",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "currency_setup",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "vat_&_tax_setup",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "pickup_point_setup",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "smtp_settings",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "payment_methods_configurations",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "order_configuration",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "file_system_&_cache_configuration",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "social_media_logins",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "facebook_chat",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "facebook_comment",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "analytics_tools_configuration",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "google_recaptcha_configuration",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "google_map_setting",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "google_firebase_setting",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "shipping_configuration",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "shipping_country_setting",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "manage_shipping_states",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "manage_shipping_cities",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "manage_zones",
                "section" => "setup_configurations",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_users",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_user",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_user",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_user",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_user_roles",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_user_role",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_user_role",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_user_role",
                "section" => "user",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "server_status",
                "section" => "system",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "manage_addons",
                "section" => "system",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "admin_dashboard",
                "section" => "system",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_dynamic_popups",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_dynamic_popups",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_dynamic_popups",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_dynamic_popups",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "publish_dynamic_popups",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_custom_alerts",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_custom_alerts",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_custom_alerts",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_custom_alerts",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "publish_custom_alerts",
                "section" => "marketing",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "notification_settings",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_all_notification_types",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "add_notification_types",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "edit_notification_types",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_notification_types",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "notification_types_status_update",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "send_custom_notification",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "view_custom_notification_history",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "name" => "delete_custom_notification_history",
                "section" => "notification",
                "guard_name" => "web",
                "created_at" => $now,
                "updated_at" => $now,
            ],
        ]);
    }
}
