<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $now = date("Y-m-d H:i:s");

        DB::table("business_settings")->insert([
            [
                "type" => "home_default_currency",
                "value" => "27",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "system_default_currency",
                "value" => "27",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "currency_format",
                "value" => "1",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "symbol_format",
                "value" => "1",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "no_of_decimals",
                "value" => "2",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "google_analytics",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "facebook_login",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "google_login",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "twitter_login",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "facebook_chat",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "email_verification",
                "value" => "1",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "current_version",
                "value" => "1.0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "maintenance_mode",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "conversation_system",
                "value" => "1",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "facebook_pixel",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "google_recaptcha",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "header_logo",
                "value" => "2",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "show_language_switcher",
                "value" => "on",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "show_currency_switcher",
                "value" => "on",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "header_stikcy",
                "value" => "on",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "footer_logo",
                "value" => "2",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "about_us_description",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "contact_address",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "contact_phone",
                "value" => "01773516661",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "contact_email",
                "value" => "info@wellbeing.com",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "widget_one_labels",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "widget_one_links",
                "value" => '["#","#","#"]',
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "widget_one",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "frontend_copyright_text",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "show_social_links",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "facebook_link",
                "value" => "#",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "twitter_link",
                "value" => "#",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "instagram_link",
                "value" => "#",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "youtube_link",
                "value" => "#",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "linkedin_link",
                "value" => "#",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "payment_method_images",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_slider_images",
                "value" => "[]",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_slider_links",
                "value" => "[]",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner1_images",
                "value" => "[]",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner1_links",
                "value" => "[]",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner2_images",
                "value" => "[]",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner2_links",
                "value" => "[]",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_categories",
                "value" => "[]",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "website_name",
                "value" => "Wellbeing",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "site_motto",
                "value" => "Better Health Channel",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "site_icon",
                "value" => "1",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "base_color",
                "value" => "#f01864",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "base_hov_color",
                "value" => "#e62e04",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "meta_title",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "meta_description",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "meta_keywords",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "meta_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "site_name",
                "value" => "Wellbeing Dashboard",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "system_logo_white",
                "value" => "2",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "system_logo_black",
                "value" => "2",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "timezone",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "admin_login_background",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "decimal_separator",
                "value" => "1",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "header_menu_labels",
                "value" =>
                '["Home","Flash Sale","Blogs","All Brands","All Categories"]',
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "header_menu_links",
                "value" =>
                '["http:\\/\\/localhost\\/wellbeing\\/","http:\\/\\/localhost\\/wellbeing\\/flash-deals","http:\\/\\/localhost\\/wellbeing\\/blog","http:\\/\\/localhost\\/wellbeing\\/brands","http:\\/\\/localhost\\/wellbeing\\/categories"]',
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "google_map",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "google_firebase",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "secondary_base_color",
                "value" => "#13814C",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "secondary_base_hov_color",
                "value" => "#0f6f41",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "header_nav_menu_text",
                "value" => "light",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "homepage_select",
                "value" => "classic",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "admin_login_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "customer_login_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "customer_register_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "seller_login_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "seller_register_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "delivery_boy_login_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "forgot_password_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "password_reset_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "phone_number_verify_page_image",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "authentication_layout_select",
                "value" => "boxed",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "slider_section_full_width",
                "value" => "0",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "slider_section_bg_color",
                "value" => "#dedede",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner4_images",
                "value" => null,
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner4_links",
                "value" => null,
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner5_images",
                "value" => null,
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner5_links",
                "value" => null,
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner6_images",
                "value" => null,
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_banner6_links",
                "value" => null,
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "custom_alert_location",
                "value" => "bottom-left",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "notification_show_type",
                "value" => "only_text",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_categories_section_bg_color",
                "value" => "#f2f4f5",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_categories_content_bg_color",
                "value" => "#ffffff",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_categories_content_outline",
                "value" => "0",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "home_categories_content_outline_color",
                "value" => "#000000",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "uploaded_image_format",
                "value" => "default",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "use_floating_buttons",
                "value" => "1",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "topbar_banner",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "topbar_banner_medium",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "topbar_banner_small",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "topbar_banner_link",
                "value" => "https://wellbeing.fouraxiz.com",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "helpline_number",
                "value" => "+880 1956 734 683",
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "about_us_description",
                "value" =>
                'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "play_store_link",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "app_store_link",
                "value" => null,
                "lang" => null,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "contact_address",
                "value" =>
                "House : 25, Road No: 2, Block A, Mirpur-1, Dhaka 1216",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "footer_title",
                "value" => "Wellbeing",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "footer_description",
                "value" =>
                'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "frontend_copyright_text",
                "value" =>
                "Copyrights © 2024. All Rights Reserved By Wellbeing Dashboard.",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "widget_one",
                "value" => "Quick Links",
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "type" => "widget_one_labels",
                "value" => '["About Us","Contact Us","Help Center"]',
                "lang" => "en",
                "created_at" => $now,
                "updated_at" => $now,
            ],
        ]);
    }
}
